//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Actividad2(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================


	wire [7:0] n1; 
	wire [7:0] n2; 
	wire [7:0] n3; 
	wire [7:0] n4; 
	wire [7:0] n5; 
	wire [7:0] n6; 
	wire [7:0] n7; 
	wire [7:0] n8; 

//=======================================================
//  Structural coding
//=======================================================

	DM1 demultiplexor(
		.reloj(CLOCK_50),
		.sel(KEY[2:0]),
		.i(SW[7:0]),
		.s1(n1),
		.s2(n2),
		.s3(n3),
		.s4(n4),
		.s5(n5),
		.s6(n6),
		.s7(n7),
		.s8(n8)
	);

	DM2 demultiplexor(
		.reloj(CLOCK_50),
		.sel(KEY[2:0]),
		.i(SW[7:0]),
		.s1(n1),
		.s2(n2),
		.s3(n3),
		.s4(n4),
		.s5(n5),
		.s6(n6),
		.s7(n7),
		.s8(n8)
	);
endmodule

/*
module Actividad2(
	input [9:0] SW,
	output [9:0] LEDR
);



//=======================================================
//  REG/WIRE declarations
//=======================================================


//=======================================================
//  Structural coding
//=======================================================

	D d1(
		.n1(SW[1:0]),
		.n2(SW[3:2]),
		.n3(SW[5:4]),
		.n4(SW[7:6]),
		.s1(LEDR[1:0]),
		.s2(LEDR[3:2]),
		.s3(LEDR[5:4]),
		.s4(LEDR[7:6]),
		);
		
endmodule
/*
