ARDMK_DIR = ../../arduino-makefile
ARDUINO_DIR = ../../ide-arduino
BOARDS_TXT = ../../ide-arduino/hardware/arduino/avr/boards.txt
AVR_TOOLS_DIR = ../../ide-arduino/hardware/tools/avr/
ARDUINO_LIBS = LiquidCrystal
ARDUINO_QUIET = 1
include ../../arduino-makefile/Arduino.mk
