
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Actividad3(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);

	sopc sopc1(
		.clk_clk(CLOCK_50),
		.pio_in_export(SW[7:0]),
		.pio_out_export(LEDR[7:0]),
		.reset_reset_n(KEY[0])
	);
	


//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================



endmodule
